compile_pdf:
  stage: build
  image: aergus/latex
  script:
    - apt-get update -qy
    - apt-get install -y python python-pip
    - pip install -r requirements.txt
    - cd latex
    - latexmk -pdf -shell-escape thesis.tex
  artifacts:
    paths:
      - latex/thesis.pdf

pages:
  stage: deploy
  script:
    - mkdir public  # create a folder called public
    - cp latex/thesis.pdf public  # copy the pdf file into the public folder
  artifacts:
    paths:
      - public  # instruct GitLab to keep the public folder
  only:
    - master  # deploy the pdf only for commits made to the master branch
