compile_pdf:
  stage: build
  image: timnn/texlive  # use a Docker image for LaTeX from https://hub.docker.com/
  before_script:
    - cd latex
  script:
    - pdflatex thesis.tex
    - bibtex thesis.aux
    - pdflatex thesis.tex
    - pdflatex thesis.tex
  artifacts:
    paths:
      - latex/thesis.pdf  # instruct GitLab to keep the main.pdf file

pages:
  stage: deploy
  script:
    - mkdir public  # create a folder called public
    - cp latex/thesis.pdf public  # copy the pdf file into the public folder
  artifacts:
    paths:
      - public  # instruct GitLab to keep the public folder
  only:
    - master  # deploy the pdf only for commits made to the master branch
