name: Build LaTeX into pdf and release that on gh-pages

on:
  push:
    branches:
    - master

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        working_directory: latex/
        root_file: thesis.tex
        args: "-pdf -shell-escape"
